# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf0717637b9faf53551f5ce0e178e8acb3565f3af7dda4c0d5122d0455a9a04a6252e639f35489f653cd0ed572d86d24d55301a63918dad3022a4efc1310e1f9

test:
  secret_key_base: cd3e72b54b0844a0405c1249d2ac09a3fffad0c875839719042864780815ea490af5c9d3455e981eade764abee9151ff05faff62db122867fdac97d1709152c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
